name: Reproducible Bug Report
description: Get much faster response time by **forking this repo, reproducing the bug, and then submitting it was a PR with the title "[Issue] ..."**
labels: [Bug]
body:
  - type: textarea
    attributes:
      label: Current Behavior
      description: Describe what's happening in 1-2 sentences.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Tamagui Version
      render: Markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: Reproduction
      render: Markdown
    validations:
      required: true
  - type: textarea
    attributes:
      label: System Info
      render: Markdown
      description: |
        - Output of `npx envinfo --system --npmPackages --binaries --browsers`
