name: Push Updates
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
jobs:
  push-updates:
    runs-on: ubuntu-latest
    steps:
      #   - id: checkout
      #     name: Checkout
      #     uses: actions/checkout@v3
      - id: push-updates
        name: Push Updates
        uses: tamagui/takeout-bot@main
